language: python
install:
  - pip install -q $DJANGO
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - DJANGO="Django>=1.4,<1.5"
  - DJANGO="Django>=1.5,<1.6"
script: python recommends/tests/runtests.py
