language: python
install:
  - pip install -q $DJANGO six
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="Django>=1.10,<1.11"
    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10"
before_script:
  - "export PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH;"
script: python django_zipfile/tests/runtests.py
