language: python
install:
  - pip install -q $DJANGO
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - DJANGO="Django>=1.5,<1.6"
before_script:
  - "export PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH;"
script: python django_zipfile/tests/runtests.py
