language: python
install:
  - pip install -q $DJANGO six --use-mirrors
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - DJANGO="Django>=1.3,<1.4"
  - DJANGO="Django>=1.4,<1.5"
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"
before_script:
  - "export PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH;"
script: python django_zipfile/tests/runtests.py
